#!/usr/bin/env python3
"""
创建测试用的 PDF 文件
"""

def create_simple_pdf(filename="test_document.pdf"):
    """创建一个简单的测试PDF文件"""
    
    # 简单的 PDF 内容
    pdf_content = """%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
  /Font <<
    /F1 <<
      /Type /Font
      /Subtype /Type1
      /BaseFont /Helvetica
    >>
  >>
>>
>>
endobj

4 0 obj
<<
/Length 200
>>
stream
BT
/F1 24 Tf
100 700 Td
(AirPrint Test Document) Tj
0 -50 Td
/F1 16 Tf
(Generated by Python) Tj
0 -30 Td
(Time: 2025-08-06) Tj
0 -30 Td
(Status: Ready for printing) Tj
0 -50 Td
/F1 12 Tf
(This is a test PDF document created) Tj
0 -20 Td
(specifically for testing our AirPrint service.) Tj
ET
endstream
endobj

xref
0 5
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000356 00000 n 
trailer
<<
/Size 5
/Root 1 0 R
>>
startxref
406
%%EOF"""

    try:
        with open(filename, 'w') as f:
            f.write(pdf_content)
        print(f"✅ 测试 PDF 文件已创建: {filename}")
        return filename
    except Exception as e:
        print(f"❌ 创建 PDF 文件失败: {e}")
        return None

if __name__ == "__main__":
    create_simple_pdf()